name: Vendo arquivos compartilhados entre steps

on:
  push:
    branches:
      - main
    
jobs:
  entre-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versão do ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o Curso de github Actions Linuxtips" >mensage.txt

      - name: Listar arquivos
        run: ls -lha

      - name: Le conteudo do arquivo
        run: cat mensage.txt

